### ISSUE TITLE
🧐[config/config.ts下的chainWebpack配置 ts一直报错]

### ISSUE THREAD

**Issue by jianjian-commits** [ant-design/ant-design-pro#10054]
chainWebpack: (config: any) => {
    config.
  }

不能将类型“(config: any) => void”分配给类型“(() => any) & Function”。
  不能将类型“(config: any) => void”分配给类型“() => any”。ts(2322)
pluginConfig.d.ts(128, 1): 所需类型来自属性 "chainWebpack"，在此处的 "ConfigType" 类型上声明该属性

**Comment by ngwszsd** [comment]
大哥你能不能提点有建设性的 这ts一直报错是你的问题你找谁解决呢

**Comment by judeebene** [comment]
is there any example property signature to match "(() => any) & Function"

**Comment by anran758** [comment]
Copying the example given on the document of antd pro will throw an error because the type function generated by default does not match.

![image](https://user-images.githubusercontent.com/23024075/185113489-eba0c9f9-87c6-4dca-a3b3-d9095f5a65af.png)
![image](https://user-images.githubusercontent.com/23024075/185113971-e59e2ef0-1d7f-4d26-b10a-5a98b4d3ba3c.png)
