### ISSUE TITLE
Affix / sticky header problem when scrolling dropdowns / popovers

### ISSUE THREAD

**Issue by steffany-cruz** [ant-design/ant-design-pro#10422]
### Reproduction link

[https://preview.pro.ant.design/form/basic-form](https://preview.pro.ant.design/form/basic-form)

### Steps to reproduce

I used the ant pro site to show that this is a real problem with the components z-index, **but it's also a problem with ant.design's Affix component.**

1. At the link provided, open a component that contains a dropdown/popover (ex.: DatePicker component opens a dropdown to select date)
2. With the dropdown opened, scroll to the bottom of the page
3. You can see that the dropdown passes above the fixed header.

### What is expected?

When using a fixed header or a header with Affix, all the popovers and dropdowns shouldn't pass above the header.

### What is actually happening?

All popovers / selects / dropdowns / date pickers are passing above the Affix component or sticky headers when opened. I tryed to put a higher z-index at the header but it affects drawers and modals, the fixed header goes above them. It seems like the z-index of all these components mentioned aren't well prepared for this type of feature (fixed header/Affix)

| Environment | Info |
| --- | --- |
| antd | 4.18.6 |
| React | 17.0.2 |
| System | pop-os |
| Browser | all |

---
I'd really like to know if this will be fixed because it's a real important feature for my team. Or at least know if this will be in the road to a future fix.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! Thank you for reaching out about this issue. It sounds like you are experiencing a problem with the Ant Design Affix component and sticky headers when scrolling dropdowns and popovers. 

One solution to this problem is to set a higher z-index on the Affix component and the header, so that they overlap any other components that may have a default lower z-index. However, as you mentioned, this can cause other problems with drawers and modals, where the fixed header may cover them. 

Another solution is to use `position: sticky` instead of `position: fixed`. This works in most modern browsers, except for IE11. Here is an example of how it can be implemented:

```css
#sticky-header {
  position: sticky;
  top: 0;
  z-index: 100;
  background-color: white;
}
```

In this example, `#sticky-header` is the ID of your header element, and `z-index: 100;` will ensure that it appears above any other elements on the page. 

You can find more information and browser compatibility for sticky positioning in the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning).

I hope this helps! Let me know if you have any other questions or concerns.
