### ISSUE TITLE
🐛 [BUG]如何在V5版本中使用脚手架内置less变量?

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro#10587]
### 🐛 bug 描述
如[文档](https://pro.ant.design/zh-CN/docs/less#indexless-1)所述, 这样使用会报如下异常:  
```
@import '~antd/es/style/themes/default.less';
^
Less resolver error:
'~antd/es/style/themes/default.less' wasn't found. Tried - D:\DeskTop\Work\xxx\src\pages\User\Login\~antd\es\style\themes\default.less,npm://~antd\es\style\themes\default.less,~antd\es\style\themes\default.less

Webpack resolver error details:
resolve '~antd/es/style/themes/default.less' in 'D:\DeskTop\Work\xxx\src\pages\User\Login'
  Parsed request is a module
  using description file: D:\DeskTop\Work\xxx\package.json (relative path: ./src/pages/User/Login)
    using description file: D:\DeskTop\Work\xxx\package.json (relative path: ./src/pages/User/Login/~antd/es/style/themes/default.less)
      no extension
        D:\DeskTop\Work\xxx\src\pages\User\Login\~antd\es\style\themes\default.less doesn't exist
      .less
        D:\DeskTop\Work\xxx\src\pages\User\Login\~antd\es\style\themes\default.less.less doesn't exist
      .css
        D:\DeskTop\Work\xxx\src\pages\User\Login\~antd\es\style\themes\default.less.css doesn't exist
      as directory
        D:\DeskTop\Work\xxx\src\pages\User\Login\~antd\es\style\themes\default.less doesn't exist
    resolve as module
      D:\DeskTop\Work\xxx\src\pages\User\Login\node_modules doesn't exist or is not a directory
      D:\DeskTop\Work\xxx\src\pages\User\node_modules doesn't exist or is not a directory
      D:\DeskTop\Work\xxx\src\pages\node_modules doesn't exist or is not a directory
      D:\DeskTop\Work\xxx\src\node_modules doesn't exist or is not a directory
      looking for modules in D:\DeskTop\Work\xxx\node_modules
        D:\DeskTop\Work\xxx\node_modules\~antd doesn't exist
      D:\DeskTop\Work\node_modules doesn't exist or is not a directory
      D:\DeskTop\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory

Webpack resolver error missing:
undefined


      Error in D:\DeskTop\Work\xxx\src\pages\User\Login\index.less (line 1, column 0
```
经查看`node_modules`下未发现对应less文件, **所以是文档没更新???**
该如何在V5版本中使用脚手架内置less变量?

### 📷 复现步骤 | Recurrence steps
- `npx @ant-design/pro-cli create myapp`, `yarn install`
- 在任一页面内依据[文档](https://pro.ant.design/zh-CN/docs/less#indexless-1)引入内置less
-  `yarn start`

### 🏞 期望结果 | Expected results

可以正常使用内置less变量

### 💻 复现代码 | Recurrence code

如上

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本: 4.0.52
- 浏览器环境: chrome
- 开发环境: windows 11

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你提供的信息，可能问题出在你的`less`编译配置上。你可以在`.umirc.ts`或者`config/config.ts`中找到`less-loader`配置，然后添加`less`的`alias`映射，这样在引用的时候就可以找到对应的文件了。例如，下面是一个`less-loader`的配置示例：

```js
{
  loader: 'less-loader',
  options: {
    // 指定额外的 less 文件, 通常是一些全局变量的定义文件
    // 注意, 这里需要使用正确的相对路径, 配合 Webpack.ProvidePlugin 使用可以全应用中导入
    additionalData: `@import "@/styles/global.less";`,
    // 通过设置全局变量可以直接在 less 文件使用 $ 或者 @ 修饰符
    globalVars: {
      brand_primary: '#1DA57A',
      brand_primary_tap: '#1FA67A'
    },
    // alias 映射, 定位 antd 中的 less
    // 通过这种配置方式可以在项目中像这样导入样式 @import '~antd/lib/button/style/index'
    // 避免了 Webpack 树摇除了一些样式之后在编译时找不到对应的 less 文件的问题
    // 这里的 '~' 符号就意味着 antd 的目录位置
    alias: {
      '@ant-design/icons/lib/dist$': path.resolve(__dirname, '../src/styles/icons.js'),
      '@ant-design/icons/lib/dist/lib': path.resolve(__dirname, '../src/styles/custom-ant-icons.less'),
      '~antd': path.resolve(__dirname, '../../node_modules/antd')
    }
  }
},
```

其中，`alias`需要根据你自己的项目情况来修改。如果你的`less`文件引入的是完整的`antd/es`路径，你需要在`alias`中添加对应路径的映射。例如，你在`less`文件中这样引入`default.less`:

```less
@import '~antd/es/style/themes/default.less';
```

那么，对应的`alias`映射应该这样设置：

```js
alias: {
  // 其它映射
  '~antd': path.resolve(__dirname, '../../node_modules/antd'),
  // 添加映射
  '~antd/es': path.resolve(__dirname, '../../node_modules/antd/es')
}
```

这样设置之后，就可以正确地找到对应的`less`文件了。同时，你也可以根据自己的业务需要自己定义一些`less`文件，并将其添加到`additionalData`选项中，比如：

```js
additionalData: `
  @import '@/styles/common.less';
  @import '@/styles/color.less';
  @import '@/styles/font.less';
`
```

这样你就可以在任意地方直接使用定义的变量，而不需要再次引入`less`文件了。希望对你有所帮助！

**Comment by renanwilliam** [comment]
same issue here

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hello, according to the information you provided, the issue is related to the built-in LESS variables in Ant Design Pro v5. As a GitHub issue assistant who can only handle frontend problems related to React, I assume that you are using React and the Ant Design Pro v5 in your project.

In order to use the built-in LESS variables in Ant Design Pro v5, you can import the LESS files from the `antd` package directly in the `less` file of your component. An example of importing the `default.less` file from the `antd` package is as follows:

```less
@import "~antd/dist/antd.less";
```

If you want to override some of the variables in the `antd.less` file, you can import your own LESS file that defines these variables after importing the `antd.less` file. An example of overriding the `@primary-color` variable is as follows:

```less
@import "~antd/dist/antd.less";
@import "./custom.less";

@primary-color: #d82b7b;  // override the primary color
```

In this example, `custom.less` is a LESS file that defines variables.

Please note that you also need to configure the `less-loader` properly in your project to enable the compilation of the LESS files. You can add the `less-loader` to the Webpack configuration file of your project, and set the `modifyVars` or `javascriptEnabled` option of the `less-loader` according to your needs. An example of the Webpack configuration for the `less-loader` is as follows:

```js
{
  test: /\.less$/,
  use: [
    'style-loader',
    'css-loader',
    {
      loader: 'less-loader',
      options: {
        modifyVars: {
          'primary-color': '#d82b7b',  // override the primary color
        },
        javascriptEnabled: true,
      },
    },
  ],
},
```

In this example, the `modifyVars` option is used to override the `@primary-color` variable, and the `javascriptEnabled` option is set to `true` to allow JavaScript in the LESS files.

I hope this information can help you. If you have any further questions, please feel free to ask.

**Comment by chenshuai2144** [comment]
look here 

https://ant.design/docs/react/migration-v5-cn
