### ISSUE TITLE
🐛 [BUG] 开启多页签并固定 黑暗模式下背景色问题

### ISSUE THREAD

**Issue by 1275727217** [ant-design/ant-design-pro#10845]
### 🐛 bug 描述
ant design pro v6 
开启多页签配置 并且设置hasFixedHeader: true 的时候 页签栏背景色和主题不符, 取消固定表头后 黑暗模式下样式正常

### 📷 复现步骤 | Recurrence steps
  keepalive: [/./],
  tabsLayout: {
    hasDropdown: true,
    hasFixedHeader: true,
  },

![image](https://github.com/ant-design/ant-design-pro/assets/38625419/0fd29eb6-3d4b-4de9-9dbd-56d748ae39f4)

### © 版本信息

- Ant Design Pro 版本:  v6
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by raoxinsong** [comment]
this project is not update?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


I apologize for the confusion, but as a text-based AI, I cannot access or view files or images directly from GitHub. However, I can provide some general guidance on how to troubleshoot and fix the issue you described.

It seems that you are using Ant Design Pro v6 and encountering a problem with the background color of the tabs bar when enabling the tabsLayout with hasFixedHeader set to true in dark mode. To resolve this issue, you can try the following steps:

1. Verify the Ant Design Pro version: Make sure you are using the latest version of Ant Design Pro v6. You can check for any updates or bug fixes in the official Ant Design Pro repository: https://github.com/ant-design/ant-design-pro

2. Check for related issues: Look for any open or closed issues on the Ant Design Pro repository that may address this problem. You can search using relevant keywords, such as "tabsLayout" or "dark mode background color."

3. Custom CSS workaround: If there is no immediate solution provided, you can try overriding the CSS to fix the background color issue. You can inspect the element using the browser's developer tools and find the relevant CSS class or selector. Then, create a custom CSS file in your project and target that class/selector to set the desired background color.

Here's an example of how you can override the CSS for the tabs bar background color:

```css
/* Assuming the class for the tabs bar is .tabs-bar */
.tabs-bar {
  background-color: #000000; /* Replace with your desired background color */
}
```

4. Documentation and resources: Refer to the official Ant Design Pro documentation for more information on customizing themes and styling. You can find the documentation here: https://pro.ant.design/docs/style-settings

If you encounter any specific error messages or need further assistance, please provide more details so that I can assist you better.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


#### 解决方案
这个问题可能是由于 Ant Design Pro V6 的一个 bug 导致的。你可以尝试以下解决方案来解决这个问题：

1. 更新 Ant Design Pro 版本：首先，请确保你正在使用最新版本的 Ant Design Pro。检查是否有可用的更新版本，尝试升级到最新版本并重新运行你的应用程序。

2. 检查多页签样式配置：确认你的多页签样式配置是否正确。确保你已经正确设置了 `hasFixedHeader: true` 以及其他相关的样式配置，并且没有其他错误的配置项。

3. 自定义样式修改：你可以尝试在你的项目中自定义样式，以修复这个问题。你可以通过覆盖默认的 Ant Design Pro 样式，并添加自定义的样式来解决背景色问题。你可以在你的样式文件中添加以下代码来修改页签栏的背景色：

```css
/* 自定义页签栏样式 */
.ant-pro-tabs-top-bar,
.ant-pro-tabs-list-wrapper {
  background-color: [你想要的背景色] !important;
}
```

请将 `background-color` 替换为你想要的背景色。

4. 反馈给 Ant Design Pro 团队：如果以上方法都无法解决你的问题，你可以将这个 bug 反馈给 Ant Design Pro 团队。他们可能会帮助你解决这个问题，或在未来的版本中修复。

#### 相关文档

1. Ant Design Pro V6 官方文档：[https://pro.ant.design/](https://pro.ant.design/)
2. Ant Design Pro GitHub 仓库：[https://github.com/ant-design/ant-design-pro](https://github.com/ant-design/ant-design-pro)
3. Ant Design 官方文档：[https://ant.design/](https://ant.design/)
4. Ant Design GitHub 仓库：[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

**Comment by chenshuai2144** [comment]
多标签页不是官方维护的，你要去相应的插件下面找维护者
