### ISSUE TITLE
Ant Design Pro Nested Layout Problem

### ISSUE THREAD

**Issue by Samandareshmamatov** [ant-design/ant-design-pro#10980]
I want to use nested layout. But the children prop in CustomLayout is coming undefined 😐.
In Custom Layout, the components on each page should come as children. But children: undefined and my pages remain empty. What is the problem in this case: importing a component or  Is the architecture wrong when creating a nested layout?
What is the right way, Give me a solution

```
// config/routes.ts
export default [
  {
    path: '/',
    component: '../layout/index',
    menu: {
      flatMenu: true,
    },
    routes: [
      {
        path: '/',
        redirect: '/overview',
      },
      {
        path: '/overview',
        component: 'Overview/index',
        menu: {
          name: 'overview',
          icon: 'testicon',
        },
      },
    ],
  },
];

// example : src/layout/index.tsx 
const CusomLayout= ({ children }) => children;
export default CusomLayout;

```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


The issue you are facing is due to the incorrect usage of the children prop in your CustomLayout component. The correct way to pass components as children is by using the React children prop. 

Here's how you can modify your code to fix the issue:

```tsx
// config/routes.ts
export default [
  {
    path: '/',
    component: '../layout/index',
    menu: {
      flatMenu: true,
    },
    routes: [
      {
        path: '/',
        redirect: '/overview',
      },
      {
        path: '/overview',
        component: '../pages/Overview', // modify the component path
        menu: {
          name: 'overview',
          icon: 'testicon',
        },
      },
    ],
  },
];

// example : src/layout/index.tsx 
const CustomLayout = ({ children }) => {
  return <div>{children}</div>;
};

export default CustomLayout;
```

In the above code, make sure the path to the `Overview` component is correctly specified. Also, wrap the `children` prop with a wrapper element, in this case, a `<div>`, to render the components correctly.

Additionally, ensure that your component file names and paths are correct to import the components properly.

For more information on working with React components and passing children, you can refer to the React documentation:
- React Children: https://reactjs.org/docs/react-api.html#reactchildren
