### ISSUE TITLE
Conform to `ant-design/babel-plugin-import` conventions for style directory

### ISSUE THREAD

**Issue by Sitch** [ant-design/ant-design-pro#1099]
Currently you cannot use the ant-design/babel-plugin-import to pull in ant-design-pro, the same way you would with antd.

Expected Usage:
```["import", { libraryName: "ant-design-pro", libraryDirectory: "es", style: true }]```

That is because the index.less files are at the component level rather than in their own styles dir, i.e., ./styles/index.less

**Comment by chenshuai2144** [comment]
This idea is exactly what we want to do.
Since we used css-moudle, importing less files does not hit the generated dom.
Plan this is the feature that will be introduced in the next version
You can see https://github.com/ant-design/ant-design-pro-site/pull/153.
This is a gradual matter and hopes for understanding

thank you

**Comment by chenshuai2144** [comment]
#1317
