### ISSUE TITLE
something wrong with ci

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#1221]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/507615/38173084-8bf17d1e-35ea-11e8-95bd-a9ed06db47fb.png">

用例报错了但是结果是成功的。

https://ci.appveyor.com/project/afc163/ant-design-pro/build/1.0.1152

**Comment by afc163** [comment]
https://travis-ci.org/ant-design/ant-design-pro/jobs/360848688

travis 也有问题。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1133

和这个一样吧,别名的问题

**Comment by afc163** [comment]
这个问题是 test 失败了，ci 还提示成功。

**Comment by chillyistkult** [comment]
@afc163 @chenshuai2144  Even if you fix the alias issue, the tests will still not work on travis or circleci. Because Jest always returns with exit code 0! Build providers will not mark the test as failed.

https://github.com/palmerj3/jest-junit/issues/2

I guess you have to upgrade jest dependencies in roadhog / umi.

**Comment by chenshuai2144** [comment]
@chillyistkult  thank you!

**Comment by afc163** [comment]
> I guess you have to upgrade jest dependencies in roadhog / umi.

@sorrycc

**Comment by afc163** [comment]
https://github.com/afc163/umi-dva-user-dashboard/pull/1

umi test 有些问题。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/1414
