### ISSUE TITLE
本地无任何错误信息，build到线上后报错umi.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by jerryyan1990** [ant-design/ant-design-pro#3016]
在本地没有任何错误信息，但是build到线上后报错。
![bug](https://user-images.githubusercontent.com/12929365/49206347-c05dbc00-f3ec-11e8-93df-4e2657313bf3.png)
是用的是最新版的ant design pro 昨天才npm安装的。

**Comment by chenshuai2144** [comment]
promise的错误？

**Comment by jerryyan1990** [comment]
神了个奇，今天自己好了...好了...了...

**Comment by ldwonday** [comment]
我也遇到这个错误了！
![image](https://user-images.githubusercontent.com/4630157/59419053-b76a9000-8dfc-11e9-8bd6-28e7acc3809f.png)

**Comment by beevivo6** [comment]
我们的项目也遇到了，好频繁怎么解决这个问题？？？

**Comment by beevivo6** [comment]
umi.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at u (umi.js:1)
    at u.t (umi.js:1)
    at async Promise.all (index 0)

**Comment by chenshuai2144** [comment]
试着清一下缓存

**Comment by beevivo6** [comment]
可是一直这样清缓存也不是办法啊？你们彻底解决了吗？




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            魅璃儿
                            
                            
                                
                                    邮箱：beevivo6@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


在2019年06月17日 19:09，陈帅 写道： 试着清一下缓存

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ant-design/ant-design-pro/issues/3016?email_source=notifications\u0026email_token=AHAOLMUIQSFOA4DZHFPW2DTP25WHBA5CNFSM4GHENJT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX22Q2Q#issuecomment-502638698",
"url": "https://github.com/ant-design/ant-design-pro/issues/3016?email_source=notifications\u0026email_token=AHAOLMUIQSFOA4DZHFPW2DTP25WHBA5CNFSM4GHENJT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX22Q2Q#issuecomment-502638698",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ThienMD** [comment]
same issue. Some time after deploy i met this issue. please fix it

**Comment by luckily-man** [comment]
也是这个问题，强制刷新一切正常，普通刷新就报错
![Uploading bug.png…]()
