### ISSUE TITLE
pages not optimized for mobile

### ISSUE THREAD

**Issue by kevinxh** [ant-design/ant-design-pro#34]
Overall, nice work on the ant-design and the scaffold!

Just noted that it seems the components are not optimized for mobile.
<img width="433" alt="screen shot 2017-10-27 at 4 31 38 pm" src="https://user-images.githubusercontent.com/10948652/32128649-7146c82e-bb34-11e7-83e4-2274d1fab48d.png">

**Comment by afc163** [comment]
We will import that soon, thank for reporting it!

**Comment by W1M0R** [comment]
Hi. Thanks for your efforts, great work so far. 

I think this issue should be re-opened, since most of the pages are still not optimized for mobile, especially the fullscreen pages such as the login page. Also, the navigation panel on the left takes up valuable screen space, making it even harder for the dashboard to be useful on mobile. It would be best if the navigation panel does not display on mobile, until you click on a menu button in the top bar.

**Comment by W1M0R** [comment]
The menu bar can be made responsive by setting `collapsedWidth` in the `Sider` layout component of `antd`, for example, in `BasicLayout.js`:

```
        <Sider
           ...
          collapsedWidth={0}
          ...
        >
```
