### ISSUE TITLE
url() 会引起 ModuleNotFoundError: Module not found: Error

### ISSUE THREAD

**Issue by mickeycharles** [ant-design/ant-design-pro#3586]
引入一些外部组件，如引入leaflet后， import 'leaflet/dist/leaflet.css'
在编译时会报ModuleNotFoundError: Module not found: Error: Can't resolve 'images/layers-2x.png' 的错误，看代码是因为dist/leaflet.css 中有url(images/layers-2x.png)，

其他外部组件一样, css 中若有url(***.png)就会在编译阶段报找不到***.png

**Comment by chenshuai2144** [comment]
@sorrycc

**Comment by aisuresh** [comment]
The issue is related to UMI. After hours of search able to fix the issue given in umijs/umi#1369.

Basically we need to set path.
1: open /config/config.js
2: find key: cssLoaderOptions
3: change modules:ture -> modules:false

This will solve compile time issue and build will succeed.

But you will face an issue in runtime in ant-design-pro. No map will be loaded as it is not able to find the images and icons. You will see an empty page. To solve that issue, this link guide you to few steps to relink the image from local instead of node_modules. https://www.cnblogs.com/GuliGugaLiz/p/9149956.html

Thanks,
Suresh
