### ISSUE TITLE
怎样单独发 npm

### ISSUE THREAD

**Issue by waybi** [ant-design/ant-design-pro#386]
ant-design-pro的npm包把组件都打包到lib文件夹中，我自己使用ant-design-pro的脚手架，封装自己的业务组件怎样可以像ant-design-pro这样打包发到自己的npm私有库中？

**Comment by afc163** [comment]
Due to short of hands, Ant Design team use GitHub issues to accept bug reports or discuss plans of Ant Design. So, please don't ask usage questions here. You can try to ask questions in [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your questions. Thank you for cooperation!
