### ISSUE TITLE
where to get the templates like From, List, User

### ISSUE THREAD

**Issue by qqsea** [ant-design/ant-design-pro#4571]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4338

🎯 Block
In v4 we split Pro's assets into two pieces, Layout and Pages. All interfaces are composed of these two parts. We've componentized Layout to provide development efficiency, and blocks are our solution for Pages. Each block is a page that can take its own state, localize, and even mock data and server. Umi-based capabilities allow them to be easily and quickly integrated into scaffolding.

Due to the feature of the block. Your new project will be very concise, with no extra dependencies, and no bunch of pages you can't use. It looks like this:
image.png
If you need a page from Pro, you can add it quickly via the block. In Pro's demo site we have added a button. When you want to use this page into your project, you can download this block into your project by clicking and copying the following line of code. It's as simple as going to the mall to buy a product:
