### ISSUE TITLE
🧐[问题] Question: moment.js not correctly translating English words for times

### ISSUE THREAD

**Issue by danleighton** [ant-design/ant-design-pro#7944]
### 🧐 问题描述 - Problem description

When selecting English as the language, the words inserted by moment.js remain in Chinese.
Please advise on how to correct :-)

Many thanks for all your hard work on this wonderful project!

### 🚑 其他信息 - Other information
<img width="1129" alt="Screenshot 2021-01-12 at 13 29 44" src="https://user-images.githubusercontent.com/7113864/104321810-05191400-54dc-11eb-9ea6-c2fc4b30aefe.png">
<img width="1119" alt="Screenshot 2021-01-12 at 13 36 43" src="https://user-images.githubusercontent.com/7113864/104321825-09ddc800-54dc-11eb-973a-f7174c939ca0.png">
<img width="1388" alt="port" src="https://user-images.githubusercontent.com/7113864/104322051-532e1780-54dc-11eb-9ef0-212ccc64df10.png">

**Comment by brlala** [comment]
I encountered the same problem, this seems to be a bug in umi where they left the moment-locale for English as empty.
```
localeExports.ts
  'en-US': {
    messages: {
      ...
    },
    locale: 'en-US',
    antd: {
      ...
    },
    momentLocale: '', <-----This field here should be 'en-US'
  },
```
 as of now, the workaround is to just explicitly set the moment to English language by adding `moment.locale('en-US)` to your page

**Comment by danleighton** [comment]
Thanks @brlala we do actually have that in the localeExports.ts file... It is still not working. I shall try adding to the pages and let you know if that works :-)

**Comment by danleighton** [comment]
Hmm, may be I am misunderstanding something @brlala. Would you mind giving me an example from a page of how you are importing moment.locale('en-US') specifically to the page please?

**Comment by huntdream** [comment]
The Chinese characters you point out in first picture are not related with moment.js, they mean "Action Two" in English

**Comment by brlala** [comment]
I've encounter 2 issues on the translation part:
1. Is with components [still displaying in Chinese](https://github.com/ant-design/ant-design-pro/issues/7892) if you change the default language in the config.ts.
2. Moment [display dates in Chinese](https://github.com/ant-design/ant-design-pro/issues/7944#issuecomment-758850447) Character even when the default language is set to English.

For both issue #1 and #2, the workaround I had is to add a function that's being run as each page is loaded, it's a hack, but it manages to solve my problem as of now

```
utils/language.ts

export const changeLanguage = (lang: string) => {
  setLocale(lang);
  setIntl(lang);
  moment.locale(lang);
};

pages/yourPage.ts

import { changeLanguage } from '@/utils/language';
changeLanguage('en-US'); <-- can be set dynamically from state

const Login: React.FC = () => {
    return (<>
                   {moment(entity.createdAt).format('dd, DD-MMM-YY')}    <---Related to issue 2
                   <ProFormSelect name="tags" label="Keywords" width="lg"/>    <---Related to issue 1
                </>)
}
```
By the way, like what @huntdream mentioned above, your issue is not related to moment.
