### ISSUE TITLE
npm run build 部署后，放在apache根目录中，访问出现404🧐[问题]

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#8821]
### 🧐 问题描述

1. npm run build 部署后，放在apache根目录中，访问出现404找不到页面：
Not Found
The requested URL was not found on this server.
2. 首页是可以访问的，之后的其他所有页面都无法访问
3.  请问这个该怎么处理呢

### 🚑 截图如下

![image](https://user-images.githubusercontent.com/13744175/127260670-cacd237c-8e35-4454-b2b5-97db2911b99a.png)
![image](https://user-images.githubusercontent.com/13744175/127260720-6e5f9015-d9b0-43cf-9c3a-ec57e98210d3.png)

**Comment by chenshuai2144** [comment]
<div class="s-prose js-post-body" itemprop="text">
<p>I commonly see this done with mod_rewrite:</p>

<pre><code> RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
 RewriteRule ^/(.*)$ balancer://app_cluster%{REQUEST_URI} [P,QSA,L]
</code></pre>

<p>It means "If a file does not exist on the file system, then proxy it through my mod_proxy_balancer cluster." Otherwise, if the file exists on the file system, it is simply served up by Apache relative to the defined <code>DocumentRoot</code> in your virtualhost.</p>

<p>But that's not my favorite way, mostly because it would require a <code>stat</code> system call per request.</p>

<p>With mod_proxy, you can use <code>ProxyPassMatch</code> if you have a new enough version of Apache (<a href="http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypassmatch" rel="noreferrer">see documentation</a>). Such as:</p>

<p><code>ProxyPassMatch \.(gif|jpe?g|css|js)$ !</code></p>

<p>Which uses the ! to indicate Apache should <em>not</em> proxy requests matching that regular expression.</p>

<p>If you are using an older version of Apache, you will have the <code>ProxyPass</code> directive available to you, but it only matches URI prefixes (this is my current preferred method):</p>

<pre><code>ProxyPass /images !
ProxyPass /stylesheets !
</code></pre>

<p>Of course, if you must do regular expression matching as you mentioned above, then you can simply modify the mod_rewrite rule I posted at the top to negate a match against the <code>%{REQUEST_URI}</code>.</p>

<p>Hope that helps!</p>
    </div>

**Comment by dhbyls** [comment]
> try file 也要配置的，不然就要改成hash 路由

在哪里改呢，有文档吗？

**Comment by dhbyls** [comment]
> try file 也要配置的，不然就要改成hash 路由

## 这里是配置的hash呢
```
export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
```
