### ISSUE TITLE
[Warning] The initialValues only take effect when the form is initialized, if you need to load asynchronously recommended request, or the initialValues?<Form/>:null

### ISSUE THREAD

**Issue by drizzlesconsin** [ant-design/ant-design-pro#8887]
### 🐛 bug 描述

```
The initialValues only take effect when the form is initialized, if you need to load asynchronously recommended request, or the initialValues?<Form/>:null
at BaseForm
at RequestForm
at ProForm
at div
at div
at div
at Login
at LoadableComponent
at Route
at Switch
at Route
at Switch
...
```

### 🏞 期望结果

行为大概是预期表现？是否可以优化一下，主要是觉得影响开发体验。

### 💻 复现代码

```bash
npx create-umi myapp
# ❯ ant-design-pro
# ❯ V5
```

当开启热更新时
```ts
// config/config.ts
fastRefresh: {},
```
使用表单组件 `initialValues`
```tsx
<ProForm
    initialValues={{
        autoLogin: true,
    }}
></ProForm>
```
控制台就报以上警告。
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本 [3.4.0]
- 浏览器环境 [Chrome]
- 开发环境 [e.g. mac OS]
- `@ant-design/pro-form: 1.18.3`

**Comment by chenshuai2144** [comment]
fastRefresh 是通过不停更新 props 来实现的，可以忽略掉。

另外这个只出现一次，但是可以大大的减少我们的答疑成本，不然每周都有 issue

**Comment by chenshuai2144** [comment]
fastRefresh 是通过不停更新 props 来实现的，可以忽略掉。

l这个只出现一次，但是可以大大的减少我们的答疑成本

**Comment by chao325** [comment]
我也出现了这个问题，但是我并没有使用表单。。。可以忽略他是吗？

**Comment by chenshuai2144** [comment]
恩，可以忽略的，我改了下判读

**Comment by chao325** [comment]
Thank


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] [Warning] The initialValues only take effect when the form is initialized, if you need to load asynchronously recommended request, or the initialValues?<Form/&gt;:null (#8887)





 
恩，可以忽略的，我改了下判读
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
