### ISSUE TITLE
🐛[BUG] 官网的预览地址无法显示

### ISSUE THREAD

**Issue by tanhaixiang** [ant-design/ant-design-pro#9302]
### 🐛 bug 描述

初始化基础模板：simple/TypeScript 启动后，打开页面后空白，F12出现Maximum call stack size exceeded的问题，
然后试一下官网的预览地址也是同样的问题，无法打开

### 📷 复现步骤

打开官网预览地址：https://preview.pro.ant.design，无法跳转到对应的页面，空白了

### 🏞 期望结果

启动项目后，能够正常显示

### 💻 复现代码

提供可复现的代码，仓库，或线上示例

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本:3.5.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/4711266/141752619-a71ac19d-26f1-4cef-bd90-d23c63b24c39.png)

**Comment by RiteshMakan** [comment]
For English speaking users, the Preview link is not working.

I was about to log the issue, but instead of duplicating

Seems to be an error in the console
<img width="883" alt="Screenshot 2021-11-15 at 11 44 10" src="https://user-images.githubusercontent.com/82932397/141759417-f7c2c19d-44ed-44b1-b18e-e5f93fc3941e.png">

**Comment by xahy123** [comment]
1，我也这样

**Comment by CheckCoder** [comment]
+1

**Comment by knight-peter** [comment]
+1我也遇到这个问题了。

**Comment by chenshuai2144** [comment]
fixed
